// import {
//   spfOne,
//   spfTwo,
//   spfThree,
//   spfFour,
//   bestSellerOne,
//   bestSellerTwo,
//   bestSellerThree,
//   bestSellerFour,
//   newArrOne,
//   newArrTwo,
//   newArrThree,
//   newArrFour,
// } from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,    
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Review",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: "https://cdn01.sapnaonline.com/product_media/9781542094085/md_9781542094085_061020211023776.jpg",
    productName: "400 days",
    price: "35.00",
    color: "Chetan Bhagat",
    badge: true,
    des: "'400 Days' is the story of Alia, a mother who is determined to find her missing son while grappling with a failing marriage and individuality.",
  },
  {
    _id: "202",
    img: "https://m.media-amazon.com/images/I/A1m1hAOgeEL._AC_UF894,1000_QL80_.jpg",
    productName: "Immortal Longings",
    price: "180.00",
    color: "Chloe Gong",
    badge: true,
    des: "Immortal Longings is a fiery collision of power plays, spilled blood, and romance amidst a set of deadly games.",
  },
  {
    _id: "203",
    img: "https://m.media-amazon.com/images/I/61ZRWLIH8oL._AC_UF894,1000_QL80_.jpg",
    productName: "A touch of Eternity",
    price: "25.00",
    color: "Durjoy Datta",
    badge: true,
    des: "An extraordinary story of a couple Anvesha and Druvan, who were to be perfect soulmates for each other since the time they were born. Born on the same day, at the same time, and are inseparable. But as the blurb says, when the time comes, can one stay true to their soulmate?",
  },
  {
    _id: "204",
    img: "https://m.media-amazon.com/images/I/610FSHxrCxL._UC256,256_CACC,256,256_.jpg",
    productName: "Midnight freeway",
    price: "220.00",
    color: "Vivaan Shah",
    badge: true,
    des: "Midnight Freeway is a murder mystery where a builder Yogesh Moolchandani dies one dreadful night in an accident. Police grabs Pranav Paleja for enquiry and that's how the story, the twists, the secrets come into play.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: "https://cdn01.sapnaonline.com/product_media/9781542094085/md_9781542094085_061020211023776.jpg",
    productName: "400 days",
    price: "35.00",
    color: "Chtan Bhagat",
    badge: true,
    des: "'400 Days' is the story of Alia, a mother who is determined to find her missing son while grappling with a failing marriage and individuality.",
  },
  {
    _id: 1002,
    img: "https://images-eu.ssl-images-amazon.com/images/I/71PNGYHykrL._AC_UL210_SR210,210_.jpg",
    productName: "It starts with us",
    price: "180.00",
    color: " Colleen Hoover",
    badge: true,
    des: "It Starts With Us” instead focuses on recovery and starting a new life of healthy love. It's a story about feeling loved for the first time and giving the love you believe others deserve from you.",
  },
  {
    _id: 1003,
    img: "https://m.media-amazon.com/images/I/61ZRWLIH8oL._AC_UF894,1000_QL80_.jpg",
    productName: "A touch of Eternity",
    price: "25.00",
    color: "Durjoy Datta",
    badge: true,
    des: "An extraordinary story of a couple Anvesha and Druvan, who were to be perfect soulmates for each other since the time they were born. Born on the same day, at the same time, and are inseparable. But as the blurb says, when the time comes, can one stay true to their soulmate?",
  },
  {
    _id: 1004,
    img: "https://m.media-amazon.com/images/I/610FSHxrCxL._UC256,256_CACC,256,256_.jpg",
    productName: "Midnight freeway",
    price: "220.00",
    color: "Vivaan Shah",
    badge: true,
    des: "Midnight Freeway is a murder mystery where a builder Yogesh Moolchandani dies one dreadful night in an accident. Police grabs Pranav Paleja for enquiry and that's how the story, the twists, the secrets come into play.",
  },
  {
    _id: 1005,
    img: "https://m.media-amazon.com/images/I/51Z0nLAfLmL.jpg",
    productName: "The alchemist",
    price: "35.00",
    color: "Paulo Coelho",
    badge: true,
    des: "The Alchemist is a classic novel in which a boy named Santiago embarks on a journey seeking treasure in the Egyptian pyramids after having a recurring dream about it and on the way meets mentors, falls in love, and most importantly, learns the true importance of who he is and how to improve himself .",
  },
  {
    _id: 1006,
    img: "https://m.media-amazon.com/images/I/71Chcpw13lL._AC_UF1000,1000_QL80_.jpg",
    productName: "It ends with us",
    price: "180.00",
    color: " Colleen Hoover",
    badge: false,
    des: "It Ends With Us screams out loud that it's not okay, that it's not normal, and that this cycle of abuse must end for good. It is the author's brave attempt to present the true picture of abuser, victim, and survivor",
  },
  {
    _id: 1007,
    img: "https://m.media-amazon.com/images/I/B1F+WB+FOZS._AC_UF1000,1000_QL80_.jpg",
    productName: "The Secret Garden",
    price: "25.00",
    color: "Frances Hodgson Burnett",
    badge: true,
    des: "The gardens surrounding the large property are Mary's only escape. Then, Mary discovers a secret garden, surrounded by walls and locked with a missing key. With the help of two unexpected companions, Mary discovers a way in—and becomes determined to bring the garden back to life.",
  },
  {
    _id: 1008,
    img: "https://m.media-amazon.com/images/I/71dNsRuYL7L._AC_UF894,1000_QL80_.jpg",
    productName: "You only live once",
    price: "220.00",
    color: "Stuti Changle",
    badge: false,
    des: "The story is about Alara searching for Elisha and in the process meeting Aarav and Ricky among others in Goa, but at the end, each of them realize they are searching for something more than a missing person. And that is exactly what the title translates into — You live only once..",
  },
  {
    _id: 1009,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8wnIx0RqUTa3Ax-Bi4VgPGxmRxCps2RNIfA&usqp=CAU",
    productName: "Witch king",
    price: "44.00",
    color: "Martha Wells",
    badge: true,
    des: "A fugitive witch from an oppressive fae kingdom plots to free himself from his past when his unwanted fiance, heir to the throne, forces him to return home under the threat of a life-or-death blood contract.",
  },
  {
    _id: 1010,
    img: "https://m.media-amazon.com/images/I/51o4gDSE07L.jpg",
    productName: "The Last tale of the flower Bride",
    price: "250.00",
    color: "Roshani Chokshi",
    badge: true,
    des: "In the book, a man and his mysterious wife, Indigo, return to her childhood home. There, he is forced to reckon with details he never knew about Indigo's past, particularly about her childhood best friend Azure who disappeared years before.",
  },
  {
    _id: 1011,
    img: "https://m.media-amazon.com/images/I/51H+upoqo+L.jpg",
    productName: "Divine Rivals",
    price: "80.00",
    color: "Rebecca Ross",
    badge: true,
    des: "When two young rival journalists find love through a magical connection, they must face the depths of hell, in a war among gods, to seal their fate forever. After centuries of sleep, the gods are warring again. But eighteen-year-old Iris Winnow just wants to hold her family together.",
  },
  {
    _id: 1012,
    img: "https://m.media-amazon.com/images/I/A1m1hAOgeEL._AC_UF894,1000_QL80_.jpg",
    productName: "Immortal Longings",
    price: "60.00",
    color: "Chloe Gong",
    badge: false,
    des: "Immortal Longings is a fiery collision of power plays, spilled blood, and romance amidst a set of deadly games.",
  },
  //====================================================================================================================
  {
    _id: 1013,
    img: "https://cdn.vox-cdn.com/thumbor/1HgFMuJipokAnxrmq-127wvLIPc=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/19980996/9781400079988.jpg",
    productName: "War and peace",
    price: "60.00",
    color: "Leo Tolstoy",
    badge: false,
    des: "Set during the Napoleonic Wars, the work mixes fictional narrative with chapters discussing history and philosophy. First published serially beginning in 1865, the work was rewritten and published in its entirety in 1869.",
  },

  {
    _id: 1014,
    img: "https://cdn.britannica.com/21/182021-050-666DB6B1/book-cover-To-Kill-a-Mockingbird-many-1961.jpg",
    productName: "To Kill a Mockingbird",
    price: "250.00",
    color: "Harper Lee",
    badge: true,
    des:"To Kill a Mockingbird, by American author Harper Lee, was published during the civil rights movement and uses its characters to explore the consequences of hatred and prejudice."
  },
  {
    _id: 1015,
    img: "https://m.media-amazon.com/images/I/41nGXlJ2GSL.jpg",
    productName: "1984",
    price: "60.00",
    color: "George Orwell",
    badge: false,
    des: "1984 is a dystopian novella by George Orwell published in 1949, which follows the life of Winston Smith, a low ranking member of 'the Party', who is frustrated by the omnipresent eyes of the party, and its ominous ruler Big Brother. 'Big Brother' controls every aspect of people's lives.",
  },
  {
    _id: 1016,
    img: "https://ppld.org/sites/default/files/styles/large/public/images/bookjackets/pride_0.jpg?itok=GJ7_g99r",
    productName: "Pride and Prejudice",
    price: "250.00",
    color: "Jane Austen ",
    badge: true,
    des: "Rich in comedy, romance, wit and satire, Austen's six novels are also pin-sharp reflections of her social and geographical milieu in and around Hampshire, Bath and Dorset.",
  },
  {
    _id: 1017,
    img: "https://m.media-amazon.com/images/I/71FTb9X6wsL._AC_UF894,1000_QL80_.jpg",
    productName: "The Great Gatsby",
    price: "220.00",
    color: "Scott Fitzgerald",
    badge: false,
    des: "Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan.",
  },
  {
    _id: 1018,
    img: "https://m.media-amazon.com/images/I/5158X1PVNTL._AC_UF1000,1000_QL80_.jpg",
    productName: "Ulysses",
    price: "44.00",
    color: "James Joyce",
    badge: true,
    des: "Ulysses experiments with many different literary styles and forms. Set in the offices of The Freeman's Journal, the 'Aeolus' episode is written in the journalistic style of a newspaper. Styles echo substance, but they also enhance access to inner lives.",
  },
  {
    _id: 1019,
    img: "https://images-eu.ssl-images-amazon.com/images/I/814ZhvhJ-bL._AC_UL210_SR210,210_.jpg",
    productName: "The Catcher in the Rye",
    price: "250.00",
    color: "J.D. Salinger",
    badge: true,
    des: "Holden Caulfield recalls the events of a weekend (Saturday afternoon to Monday afternoon) shortly before the previous year's Christmas, beginning at Pencey Preparatory Academy, a boarding school in Pennsylvania.",
  },
  {
    _id: 1020,
    img: "https://m.media-amazon.com/images/I/71OZJsgZzQL._AC_UF894,1000_QL80_.jpg",
    productName: "The Brothers Karamazov",
    price: "80.00",
    color: "Fyodor Dostoevsky",
    badge: true,
    des: "The Brothers Karamazov is the story of the lives of three Russian brothers who are very different in body, mind, and spirit, and are often thought of as representing those three parts of mankind It was written in 1879 to 1880 in Russia, mostly in St. Petersburg. It was published in 1879 to 1880 in a series. It is his most complicated and deep novel, and most people think it is Dostoevsky's greatest",
  },
  {
    _id: 1021,
    img: "https://m.media-amazon.com/images/I/71HOtbT2w3L._AC_UF1000,1000_QL80_.jpg",
    productName: "Brave New World",
    price: "250.00",
    color: "Aldous Huxley",
    badge: true,
    des: "Holland designed this cover for the first edition. Huxley's dystopian novel describes a future society in which technological and medical innovations are used by the state to exercise control over its citizens.",
  },
  {
    _id: 1022,
    img: "https://cdn2.wwnorton.com/wwnproducts/TRADE/0/5/9780393356250/9780393356250_300.jpg",
    productName: "The Odyssey",
    price: "220.00",
    color: "Homer",
    badge: true,
    des: "The Odyssey begins after the end of the ten-year Trojan War (the subject of the Iliad), from which Odysseus (also known by the Latin variant Ulysses), king of Ithaca, has still not returned because he angered Poseidon, the god of the sea. Odysseus' son, Telemachus, is about 20 years old and is sharing his absent father's house on the island of Ithaca with his mother Penelope and the suitors of Penelope, a crowd of 108 boisterous young men who each aim to persuade Penelope for her hand in marriage, all the while reveling in the king's palace and eating up his wealth.",
  },
  {
    _id: 1023,
    img: "https://m.media-amazon.com/images/I/81z7E0uWdtL._AC_UF1000,1000_QL80_.jpg",
    productName: "Frankenstein",
    price: "35.00",
    color: "Mary Shelley",
    badge: true,
    des: "The book tells the story of Victor Frankenstein, a Swiss student of natural science who creates an artificial man from pieces of corpses and brings his creature to life. Though it initially seeks affection, the monster inspires loathing in everyone who meets it.",
  },
  {
    _id: 1024,
    img: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Beloved_%281987_1st_ed_dust_jacket_cover%29.jpg",
    productName: "Beloved",
    price: "35.00",
    color: "Toni Morrison",
    badge: true,
    des: "he work examines the destructive legacy of slavery as it chronicles the life of a Black woman named Sethe, from her pre-Civil War days as a slave in Kentucky to her time in Cincinnati, Ohio, in 1873",
  },
  {
    _id: 1025,
    img: "https://m.media-amazon.com/images/I/81GjCVSEDAL._AC_UF894,1000_QL80_.jpg",
    productName: "The Stranger",
    price: "180.00",
    color: "Albert Camus",
    badge: true,
    des: "The first of Camus' novels published in his lifetime, the story follows Meursault, an indifferent settler in French Algeria, who, weeks after his mother's funeral, kills an unnamed Arab man in Algiers. The story is divided into two parts, presenting Meursault's first-person narrative before and after the killing.",
  },
  {
    _id: 1026,
    img: "https://cdn.kobo.com/book-images/f47d4dc8-32a6-4136-9231-084dc64f1380/1200/1200/False/a-tale-of-two-cities-464.jpg",
    productName: "A Tale of Two Cities",
    price: "25.00",
    color: "Charles Dickens",
    badge: true,
    des: "The novel tells the story of the French Doctor Manette, his 18-year-long imprisonment in the Bastille in Paris, and his release to live in London with his daughter Lucie whom he had never met. The story is set against the conditions that led up to the French Revolution and the Reign of Terror.",
  },
  {
    _id: 1027,
    img: "https://m.media-amazon.com/images/I/51W5xvphHlL.jpg",
    productName: "The Count of Monte Cristo",
    price: "220.00",
    color: "Alexandre Dumas",
    badge: true,
    des: "In the post-Napoleonic era, a young sailor from Marseilles is poised to become captain of his own ship and marry his beloved. But jealous enemies provoke his arrest, condemning Edmond Dantès to lifelong imprisonment in the infamous Château d'If.",
  },
  {
    _id: 1028,
    img: "https://m.media-amazon.com/images/I/51nH4PirA0L.jpg",
    productName: "The Scarlet Letter",
    price: "35.00",
    color: "Nathaniel Hawthorne",
    badge: true,
    des: "Set in the Puritan Massachusetts Bay Colony during the years 1642 to 1649, the novel tells the story of Hester Prynne, who conceives a daughter with a man to whom she is not married and then struggles to create a new life of repentance and dignity.",
  },
  {
    _id: 1029,
    img: "https://m.media-amazon.com/images/I/71Au8SjrwkL._AC_UF894,1000_QL80_.jpg",
    productName: "The Old Man and the Sea",
    price: "180.00",
    color: "Ernest Hemingway",
    badge: false,
    des: "The Old Man and the Sea, short heroic novel by Ernest Hemingway, published in 1952 and awarded the 1953 Pulitzer Prize for fiction. It was his last major work of fiction. The story centres on an aging fisherman who engages in an epic battle to catch a giant marlin.",
  },
  {
    _id: 1030,
    img: "https://m.media-amazon.com/images/I/91te8xMyDSL._AC_UF894,1000_QL80_.jpg",
    productName: "The Canterbury Tales",
    price: "25.00",
    color: "Geoffrey Chaucer",
    badge: true,
    des: "What is The Canterbury Tales about? Chaucer's long poem follows the journey of a group of pilgrims, 31 including Chaucer himself, from the Tabard Inn in Southwark to St Thomas à Becket's shrine at Canterbury Cathedral.",
  },
  {
    _id: 1031,
    img: "https://m.media-amazon.com/images/I/61RrjcUgL9L.jpg",
    productName: "Gulliver's Travels",
    price: "Jonathan Swift",
    badge: false,
    des: "Gulliver's Travels is a four-part prose travelogue, narrated by the fictitious persona of Lemuel Gulliver, who tells the story of his extensive global voyages, the places he has been and the people (and other creatures) he met.",
  },
  {
    _id: 1032,
    img: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546071216l/5907.jpg",
    productName: "The Hobbit",
    price: "44.00",
    color: "J.R.R. Tolkien",
    badge: true,
    des: "A fugitive witch from an oppressive fae kingdom plots to free himself from his past when his unwanted fiance, heir to the throne, forces him to return home under the threat of a life-or-death blood contract.",
  },
  {
    _id: 1033,
    img: "https://m.media-amazon.com/images/I/51b6GXNJTlL.jpg",
    productName: "Siddhartha",
    price: "250.00",
    color: "Hermann Hesse",
    badge: true,
    des: "Siddhartha, novel by Hermann Hesse based on the early life of Buddha, published in German in 1922. It was inspired by the author's visit to India before World War I. SUMMARY: The theme of the novel is the search for self-realization by a young Brahman, Siddhartha.",
  },
  {
    _id: 1034,
    img: "https://npr.brightspotcdn.com/dims4/default/3e60fe4/2147483647/strip/true/crop/314x500+0+0/resize/880x1401!/quality/90/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Flegacy%2Fsites%2Fwkar%2Ffiles%2Fdracula_book_cover.jpg",
    productName: "Dracula",
    price: "80.00",
    color: "Bram Stoker",
    badge: true,
    des: "It has no single protagonist and opens with solicitor Jonathan Harker taking a business trip to stay at the castle of a Transylvanian nobleman, Count Dracula. Harker escapes the castle after discovering that Dracula is a vampire, and the Count moves to England and plagues the seaside town of Whitby.",
  },
  {
    _id: 1035,
    img: "https://m.media-amazon.com/images/I/71ODOf3V9oL._AC_UF1000,1000_QL80_.jpg",
    productName: "The Wind in the Willows",
    price: "60.00",
    color: "Kenneth Grahame",
    badge: false,
    des: "The Wind in the Willows is a children's novel by the British novelist Kenneth Grahame, first published in 1908. It details the story of Mole, Ratty, and Badger as they try to help Mr. Toad, after he becomes obsessed with motorcars and gets into trouble.",
  },
  {
    _id: 1036,
    img: "https://m.media-amazon.com/images/I/71O7XjXaMhL._AC_UF1000,1000_QL80_.jpg",
    productName: "The Sun Also Rises",
    price: "60.00",
    color: "Ernest Hemingway",
    badge: false,
    des: "The story follows the flamboyant Brett and the hapless Jake as they journey from the wild nightlife of 1920s Paris to the brutal bullfighting rings of Spain with a motley group of expatriates. It is an age of moral bankruptcy, spiritual dissolution, unrealized love, and vanishing illusions.",
  },
  {
    _id: 1037,
    img: "https://m.media-amazon.com/images/I/81svZOFopwL._AC_UF894,1000_QL80_.jpg",
    productName: "Alice's Adventures in Wonderland",
    price: "60.00",
    color: "Lewis Carroll",
    badge: false,
    des: "Alice's Adventures in Wonderland by Lewis Carroll is a story about Alice who falls down a rabbit hole and lands into a fantasy world that is full of weird, wonderful people and animals. It is classic children's book that is also popular with adults. Personally, at 16, I found the book strange and uninteresting.",
  },
  {
    _id: 1038,
    img: "https://m.media-amazon.com/images/I/51vEv59I62L.jpg",
    productName: "Heart of Darkness",
    price: "250.00",
    color: "Joseph Conrad",
    badge: true,
    des: "Heart of Darkness examines the horrors of Western colonialism, depicting it as a phenomenon that tarnishes not only the lands and peoples it exploits but also those in the West who advance it.",
  },
  {
    _id: 1039,
    img: "https://m.media-amazon.com/images/I/61EioOixctL.jpg",
    productName: "Middlemarch",
    price: "220.00",
    color: " George Eliot",
    badge: false,
    des: "It Starts With Us” instead focuses on recovery and starting a new life of healthy love. It's a story about feeling loved for the first time and giving the love you believe others deserve from you",
  },
  {
    _id: 1040,
    img: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1549260060l/41817486.jpg",
    productName: "A Clockwork Orange",
    price: "44.00",
    color: "Anthony Burgess",
    badge: true,
    des: "A Clockwork Orange, novel by Anthony Burgess, published in 1962. Set in a dismal dystopian England, it is the first-person account of a juvenile delinquent who undergoes state-sponsored psychological rehabilitation for his aberrant behaviour.",
  },
  {
    _id: 1041,
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554582218i/6514.jpg",
    productName: "The Bell Jar",
    price: "250.00",
    color: "Sylvia Plath",
    badge: true,
    des: "The Bell Jar details the life of Esther Greenwood, a college student who dreams of becoming a poet. She is selected for a month-long summer internship as a guest editor of Ladies' Day magazine, but her time in New York City is unfulfilling as she struggles with issues of identity and societal norms.",
  },
  {
    _id: 1042,
    img:"https://m.media-amazon.com/images/I/81SXPDPFRbL._AC_UF894,1000_QL80_.jpg" ,
    productName: "The Name of the Rose",
    price: "80.00",
    color: "Umberto Eco",
    badge: true,
    des: "The hook couldn't be more obvious. When a string of strange deaths plagues a wealthy Italian abbey, Brother William of Baskerville is called to unravel the mystery. In this 14th-century thriller, every death exposes a new piece of an age-old conspiracy.",
  },
  {
    _id: 1043,
    img: "https://upload.wikimedia.org/wikipedia/commons/0/09/The_Shining_%281977%29_front_cover%2C_first_edition.jpg",
    productName: "The Shining ",
    price: "25.00",
    color: "Stephen King",
    badge: true,
    des: "Jack Torrance, his wife Wendy, and their young son Danny move into the Overlook Hotel, where Jack has been hired as the winter caretaker. Cut off from civilization for months, Jack hopes to battle alcoholism and uncontrolled rage while writing a play.",
  },
  {
    _id: 1044,
    img: "https://m.media-amazon.com/images/I/717wIEt0aNL._AC_UF1000,1000_QL80_.jpg",
    productName: "The Remains of the Day",
    price: "220.00",
    color: "Kazuo Ishiguro",
    badge: true,
    des: "Midnight Freeway is a murder mystery where a builder Yogesh Moolchandani dies one dreadful night in an accident. Police grabs Pranav Paleja for enquiry and that's how the story, the twists, the secrets come into play",
  },
  {
    _id: 1045,
    img: "https://m.media-amazon.com/images/I/81ChFcmhXDL._AC_UF894,1000_QL80_.jpg",
    productName: "The Road" ,
    price: "35.00",
    color: "Cormac McCarthy",
    badge: true,
    des: "The Alchemist is a classic novel in which a boy named Santiago embarks on a journey seeking treasure in the Egyptian pyramids after having a recurring dream about it and on the way meets mentors, falls in love, and most importantly, learns the true importance of who he is and how to improve himself .",
  },
  {
    _id: 1046,
    img: "https://m.media-amazon.com/images/I/81PJRw8JJLL._AC_UF894,1000_QL80_.jpg",
    productName: "The Goldfinch",
    price: "35.00",
    color: "Donna Tartt",
    badge: true,
    des: "'400 Days' is the story of Alia, a mother who is determined to find her missing son while grappling with a failing marriage and individuality.",
  },
];
// =================== PaginationItems End here =================
